"""One-time generator for js/vanlab-logo.generated.js.

Trims the whitespace off the VanLab logo PNG (same thresholded bbox the
Python label_generator.py applies at every run: "white" in the source
isn't pure #FFFFFF, so a zero-tolerant bbox would grab the whole canvas)
and writes it as a base64 JS global. Re-run only if the logo changes:

  python tools/make_logo_asset.py "<path to vanlab_logo.png>"
"""
import base64
import io
import os
import sys

from PIL import Image

def trimmed(path):
    img = Image.open(path).convert("RGB")
    mask = img.convert("L").point(lambda p: 255 if p < 240 else 0)
    bbox = mask.getbbox()
    if not bbox:
        return img
    pad = 6
    l, t, r, b = bbox
    l, t = max(0, l - pad), max(0, t - pad)
    r, b = min(img.width, r + pad), min(img.height, b + pad)
    return img.crop((l, t, r, b))

def main():
    if len(sys.argv) != 2:
        sys.exit("usage: python tools/make_logo_asset.py <path to vanlab_logo.png>")
    img = trimmed(sys.argv[1])
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    b64 = base64.b64encode(buf.getvalue()).decode("ascii")
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "..", "js", "vanlab-logo.generated.js")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("// GENERATED by tools/make_logo_asset.py — do not edit by hand.\n")
        f.write("// VanLab logo, whitespace-trimmed, for the 4x6 crate label.\n")
        f.write("const VanlabLogo = {\n  pngBase64:\n")
        for i in range(0, len(b64), 100):
            f.write("    '" + b64[i:i + 100] + "' +\n")
        f.write("    '',\n};\n")
    print(f"wrote {out} ({img.width}x{img.height} px, {len(b64)} base64 chars)")

if __name__ == "__main__":
    main()
